GET http://localhost:5000/api/orders/616ed135f9f10c994179d0a1 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxNTcyMDc5OWQ3ZGI5YzU3ODMzODI3MCIsImlhdCI6MTYzNDY1MTI0NiwiZXhwIjoxNjM0NjU0ODQ2fQ.X1ZxS0k0bHKBS8VbMAwRMt0dpt6TA5UjbinEdqd-s3U