const SET_CURRENT_USER = 'SET_CURRENT_USER';
const TOGGLE_CART_DROPDOWN = 'TOGGLE_CART_DROPDOWN';
const ADD_CART_ITEM = 'ADD_CART_ITEM';

export { SET_CURRENT_USER, TOGGLE_CART_DROPDOWN, ADD_CART_ITEM };
